### ISSUE TITLE
Could not load type "entity"

### ISSUE THREAD

**Issue by fromdz27** [egeloen/ivory-ordered-form#17] opened 2017-02-16 14:08 UTC
i had this error when i add 'entity' type of your field ?
is there any solution, thanks ....

**Comment by egeloen** [comment] 2017-02-16 14:59
@fromdz27 Can you please give more informations about your issue? Can't help you with your current description.

**Comment by fromdz27** [comment] 2017-02-19 08:26
hey again,
i had this form fields like this :

> `$builder
>             ->add('titre', 'text')
>             ->add('contenu', 'textarea')
>             ->add('publie', 'entity', array('position' => array('after' => 'titre')))
>             ->add('submit','submit')
>         ;`

and i had this error 

>Could not load type "entity"

 just when i insert 'entity' field type

**Comment by egeloen** [comment] 2017-02-19 08:29
What is your Symfony & PHP versions?

**Comment by fromdz27** [comment] 2017-02-19 08:30
symfony 2.7 and php 7.0

**Comment by egeloen** [comment] 2017-02-19 08:36
Last thing which can help me: do you have a stacktrace of the error?

**Comment by fromdz27** [comment] 2017-02-19 08:48
please what's 

> a stacktrace of the error

**Comment by fromdz27** [comment] 2017-02-19 08:51
ok, i get it
`Stack Trace

in vendor\symfony\symfony\src\Symfony\Component\Form\FormRegistry.php at line 83   -
            }
            if (!$type) {
                throw new InvalidArgumentException(sprintf('Could not load type "%s"', $name));
            }
            $this->resolveAndAddType($type);
at FormRegistry ->getType ('entity') 
in vendor\symfony\symfony\src\Symfony\Component\Form\FormFactory.php at line 82   +
at FormFactory ->createNamedBuilder ('contenu', 'entity', null, array()) 
in vendor\symfony\symfony\src\Symfony\Component\Form\FormBuilder.php at line 106   +
at FormBuilder ->create ('contenu', 'entity', array()) 
in vendor\symfony\symfony\src\Symfony\Component\Form\FormBuilder.php at line 269   +
at FormBuilder ->resolveChildren () 
in vendor\symfony\symfony\src\Symfony\Component\Form\FormBuilder.php at line 215   +
at FormBuilder ->getForm () 
in vendor\symfony\symfony\src\Symfony\Component\Form\FormFactory.php at line 39   +
at FormFactory ->create (object(ArticleType), object(Article)) 
in src\Sdz\BlogBundle\Controller\ArticleController.php at line 36   +
at ArticleController ->addAction (object(Request))
at call_user_func_array (array(object(ArticleController), 'addAction'), array(object(Request))) 
in app\bootstrap.php.cache at line 3140   +
at HttpKernel ->handleRaw (object(Request), '1') 
in app\bootstrap.php.cache at line 3099   +
at HttpKernel ->handle (object(Request), '1', true) 
in app\bootstrap.php.cache at line 3253   +
at ContainerAwareHttpKernel ->handle (object(Request), '1', true) 
in app\bootstrap.php.cache at line 2484   +
at Kernel ->handle (object(Request)) 
in web\app_dev.php at line 29   +`

**Comment by egeloen** [comment] 2017-02-19 08:59
Hum... Probably obvious but if you remove the position option, everything is working?

**Comment by fromdz27** [comment] 2017-02-19 10:35
Hi, again
I try this without error but no action it just render my form without position change
`$builder
            ->add('categories', 'entity', array(
                'class'    => 'SdzBlogBundle:Categories',
                'property' => 'nom',
                'multiple' => true), array('position' => 'last')
            )
            ->add('titre', 'text')
            ->add('contenu', 'textarea')
            ->add('image', new ImageType()) // Rajoutez cette ligne

            ->add('publie', 'checkbox')
            ->add('submit','submit')
        ;
`

**Comment by egeloen** [comment] 2017-02-25 19:45
@fromdz27 I give a try to your issue in the referenced commit (Symfony 2.7.24) and eveything is working fine, I'm not able to reproduce your issue.

Regarding your last message, your configuration is wrong, you need to use:

```
$builder
     ->add('categories', 'entity', array(
        'class' => 'SdzBlogBundle:Categories', 
        'property' => 'nom', 
        'multiple' => true, 
        'position' => 'last'
    )
    ->add('titre', 'text') 
    ->add('contenu', 'textarea') 
    ->add('image', new ImageType()) 
    ->add('publie', 'checkbox') 
    ->add('submit','submit') ;
```

**Comment by egeloen** [comment] 2017-02-27 21:16
@fromdz27 Have you give a try to my example?

**Comment by fromdz27** [comment] 2017-03-06 10:16
finally it's working. thank you for your help
just i fix
`array('position' => 'last')`
to
`'position' => 'last'`

**Comment by egeloen** [comment] 2017-03-06 17:30
@fromdz27 Can you please give me your exact version of PHP & Symfony (x.y.z not just x.y)? It seems strange to me than the entity type could not be loaded just due to this invalid form configuration... (the error should be more meaningful). When using 2.7.24, I can't replicate this behavior.

In all cases, closing as there is no bug in this repository and my question is much more by curiosity...

**Closed** 2017-03-06 19:30 UTC
